function smoke_test()
%SMOKE_TEST Run one deterministic PVMSim case and verify its output.

repoRoot = fileparts(fileparts(mfilename("fullpath")));
addpath(repoRoot);

moduleFile = fullfile(repoRoot, "config", "modules", "STM6-40_36.txt");
ivFile     = fullfile(repoRoot, "data", "iv", "CurvasIV_STM6-40_36.txt");

testOutputRoot = tempname;
mkdir(testOutputRoot);
cleanupObj = onCleanup(@() remove_test_output(testOutputRoot)); %#ok<NASGU>

expectedRMSE = 1.72840182019e-03;
tolerance    = 1e-8;

out = run_main( ...
    "module", moduleFile, ...
    "iv", ivFile, ...
    "seed", 42, ...
    "batchN", 1, ...
    "outRoot", testOutputRoot, ...
    "consoleOutput", false, ...
    "appVersion", "smoke-test");

actualRMSE = out.summary.rmse_obj;

assert(isfinite(actualRMSE), ...
    "Smoke test failed: RMSE_obj is not finite.");

assert(abs(actualRMSE - expectedRMSE) <= tolerance, ...
    "Smoke test failed: expected RMSE_obj %.12g A, obtained %.12g A.", ...
    expectedRMSE, actualRMSE);

requiredArtifacts = [ ...
    "run_config.json", ...
    "log.txt", ...
    "run_results.mat", ...
    "run_summary.csv", ...
    "checksums.sha256"];

for k = 1:numel(requiredArtifacts)
    artifactPath = fullfile(out.outDir, requiredArtifacts(k));
    assert(isfile(artifactPath), ...
        "Smoke test failed: missing artifact %s.", requiredArtifacts(k));
end

manifest = fileread(fullfile(out.outDir, "checksums.sha256"));
manifest = strrep(manifest, "\", "/");

requiredChecksumEntries = [ ...
    "core/RS7MSA.m", ...
    "core/mutate_RS7MSA_phase1.m", ...
    "core/mutate_RS7MSA_phase2.m", ...
    "core/clamp_val.m", ...
    "core/utils_rng.m"];

for k = 1:numel(requiredChecksumEntries)
    assert(contains(manifest, requiredChecksumEntries(k)), ...
        "Smoke test failed: checksum entry missing for %s.", ...
        requiredChecksumEntries(k));
end

fprintf("Smoke test passed: RMSE_obj = %.12g A.\n", actualRMSE);

end

function remove_test_output(folderPath)
if isfolder(folderPath)
    rmdir(folderPath, "s");
end
end